export const leads = [
    {
        id: 'USR-010',
        name: 'Alcides Antonio',
        avatar: '/assets/avatar-10.png',
        email: 'alcides.antonio@devias.io',
        status: '908-691-3242',
        address: {
            city: 'Madrid',
            country: 'Spain',
            state: 'Comunidad de Madrid',
            street: '4158 Hedge Street',
        },
    },
    {
        id: 'USR-009',
        name: 'Marcus Finn',
        avatar: '/assets/avatar-9.png',
        email: 'marcus.finn@devias.io',
        status: '415-907-2647',
    },
    {
        id: 'USR-008',
        name: 'Jie Yan',
        avatar: '/assets/avatar-8.png',
        email: 'jie.yan.song@devias.io',
        status: '770-635-2682',
        address: {
            city: 'North Canton',
            country: 'USA',
            state: 'Ohio',
            street: '4894 Lakeland Park Drive',
        },
    },
    {
        id: 'USR-007',
        name: 'Nasimiyu Danai',
        avatar: '/assets/avatar-7.png',
        email: 'nasimiyu.danai@devias.io',
        status: '801-301-7894',
        address: {
            city: 'Salt Lake City',
            country: 'USA',
            state: 'Utah',
            street: '368 Lamberts Branch Road',
        },
    },
    {
        id: 'USR-006',
        name: 'Iulia Albu',
        avatar: '/assets/avatar-6.png',
        email: 'iulia.albu@devias.io',
        status: '313-812-8947',
        address: {
            city: 'Murray',
            country: 'USA',
            state: 'Utah',
            street: '3934 Wildrose Lane',
        },
    },
    {
        id: 'USR-005',
        name: 'Fran Perez',
        avatar: '/assets/avatar-5.png',
        email: 'fran.perez@devias.io',
        status: '712-351-5711',
        address: {
            city: 'Atlanta',
            country: 'USA',
            state: 'Georgia',
            street: '1865 Pleasant Hill Road',
        },
    },
];
